version: "3.9"

services:

  database:
    image: "postgres:15-alpine3.18"
    restart: always
    ports:
      - "5432:5432"
    env_file:
      - .db.env
    volumes:
      - dbdata:/var/lib/postgresql/data
    logging:
      driver: awslogs
      options:
        awslogs-region: ${AWS_REGION}
        awslogs-group: just-a-db/database

volumes:
  dbdata: {}
