version: "3.9"

services:

  database:
    image: "postgres:17.2-alpine3.21"
    restart: always
    ports:
      - "5432:5432"
    env_file:
      - .db.env
    volumes:
      - dbdata:/var/lib/postgresql/data

  backups:
    image: just-a-db-backups
    build:
      context: ./backups
    depends_on:
      - database
    env_file:
      - .db.env
      - .backup.env

volumes:
  dbdata: {}
